### ISSUE TITLE
Srini's Comments 3/6

### ISSUE THREAD

**Issue by shivaramakrishna99** [MaayanLab/DRC-Portals#198]
1. MW → Finds LINCS studies on the top, and MW appears only on page#3
2. Search term breadcrumbs could be better formatted something like this: MW> Alzheimer’s disease>> Homo sapiens>>> CSF>>>> Mass spectrometry (Left justified on top of the Search Table on Line#1 and Count on Line#2)
3. Pagination could be on top of the Search Table on Line#2 (Right justified).
4. Reword “Results found for MW 1” to “Results found”. 
5. No options for selecting the Projects from the Search Results.
6. Filters on the Left: The Drop-down should appear after the first click. Right now, it requires 2 clicks.
7. Selecting multiple options in a given category is not there (ex: Select both Blood and CSF under Anatomy).
8. There should be a search ‘Reset/Clear’ button

10. The sidebar within the Filter box (on the left) is not working as expected. When I try to move up/down, it exits the filter box.

Solved:
9. The View icon could be something similar to:

**Comment by susrinivasan** [comment]
All these issues have been fixed. The breadcrumbs are consistent with the search term. Pagination is on the bottom being consistent with the rest of the application and as suggested by Usability Report. Projects are part of search results.Filters are on the right and drop-downs are working.Multiple selections are supported.There is a Reset All button for filters. Filters are scrollable.
