### ISSUE TITLE
Change in function of main checkbox in table header 

### ISSUE THREAD

**Issue by shivaramakrishna99** [MaayanLab/DRC-Portals#324]
Change the function of the main checkbox in the table header to download only what is seen in the current view. E.g. if 10 records are shown, download only 10 records via the checkbox. This is to distinguish it from the 'Download All' button.

![image](https://github.com/user-attachments/assets/255baf5f-d1e9-4b2e-a631-4aa8f93bdedf)

**Comment by susrinivasan** [comment]
Download Selected downloads only those that are selected (when Select All is chosen, only the records in the current page is chosen). Download All downloads all the records.
