### ISSUE TITLE
Making some github.com/nih-cfde repos readable by everyone

### ISSUE THREAD

**Issue by mano-at-sdsc** [MaayanLab/DRC-Portals#385]
When Shiva/Sumana followed the link in "The original [C2M2 documentation](https://github.com/nih-cfde/c2m2/blob/master/draft-C2M2_specification/README.md) from the CFDE Coordination Center contains more details on the concepts discussed here.") at https://info.cfde.cloud/documentation/C2M2#resources, they get an error message. This is because the repo https://github.com/nih-cfde/c2m2/tree/master/draft-C2M2_specification is private. We should allow read-only access to this repo to all.
![image_720](https://github.com/user-attachments/assets/da6ad3ea-1586-4671-b1d3-5939f162875a)

**Comment by u8sand** [comment]
@AviMaayan FYI

**Comment by AviMaayan** [comment]
I made it public...

**Comment by mano-at-sdsc** [comment]
Thanks, @AviMaayan .
