### ISSUE TITLE
Suggest linking to/describing how to use frictionless tooling in C2M2 docs 

### ISSUE THREAD

**Issue by u8sand** [MaayanLab/DRC-Portals#396]
https://framework.frictionlessdata.io/docs/getting-started.html

The frictionless CLI provides lots of useful feedback on invalid datapackage submissions with `frictionless validate`

**Comment by mano-at-sdsc** [comment]
Hi @u8sand Is the detail at https://info.cfde.cloud/documentation/C2M2 (see the screenshot below) not enough 
![image](https://github.com/user-attachments/assets/048c5bf0-b86a-4f13-a059-2bca66f84953)

**Comment by u8sand** [comment]
I guess you're right this is perfect actually. I missed it when I skimmed through
